site_name: drawarrow
site_url: https://josephbarbierdarnal.github.io/drawarrow/
repo_url: https://github.com/JosephBARBIERDARNAL/drawarrow
theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github

extra:
  analytics:
    provider: google
    property: G-XSWTDJP3CD

extra_css:
  - stylesheets/style.css

nav:
  - Home: index.md
  - Reference:
      - reference/ax_arrow.md
      - reference/fig_arrow.md
      - reference/arrow_spines.md
  - FAQ: FAQ.md

plugins:
  - mkdocs_matplotlib
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            heading_level: 3

markdown_extensions:
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
