[project]
name = "drawarrow"
version = "0.1.0"
description = "Drawing arrows for matplotlib made easy."
authors = [
  { name="Joseph Barbier", email="joseph.barbierdarnal@gmail.com" },
]
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Framework :: Matplotlib"
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib",
]

[dependency-groups]
dev = [
    "mkdocs-material>=9.6.9",
    "mkdocs-matplotlib>=0.10.1",
    "mkdocstrings-python>=1.16.5",
    "pre-commit>=4.1.0",
    "pytest>=8.3.5",
    "ruff>=0.11.0",
    "setuptools>=76.1.0",
    "ty>=0.0.1a14",
]

[build-system]
requires = [
    "setuptools",
    "setuptools-scm",
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["drawarrow"]

[tool.uv.sources]
drawarrow = { workspace = true }

[tool.ty.src]
include = ["drawarrow"]
exclude = ["tests", "sandbox.py", "docs"]

[project.urls]
Homepage = "https://github.com/JosephBARBIERDARNAL/drawarrow"
Issues = "https://github.com/JosephBARBIERDARNAL/drawarrow/issues"
